version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
        #      aws-cli: 2.3.0  # Install AWS CLI version 2
  build:
    commands:
      #  - aws --version  # Verify AWS CLI version
      # - mvn clean package
      - aws s3 cp /root/myapp.war s3://tomcat1/test/
artifacts:
  files:
    - /root/myapp.war

