version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - mvn clean package
      - aws s3 cp /root/myapp.war s3://your-bucket-name/path/to/your/war

artifacts:
  files:
    - root/myapp.war
